# Generated by Django 5.2.11 on 2026-02-06 03:23

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
        ('AI', '0003_enable_pgvector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
