# Generated by Django 5.2.11 on 2026-02-07 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_alter_textembedding_text_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textembedding',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='AI.document'),
        ),
    ]
